/**
 * src/lib/cf-bindings.ts
 *
 * Unified Cloudflare Bindings access layer.
 *
 * Strategy (priority order):
 *   1. KV cache  — fast, edge-local, avoids repeated R2 reads
 *   2. R2 bucket — direct object storage read (zero egress cost within CF)
 *   3. HTTP fetch — legacy fallback when running outside CF (e.g. `astro preview`)
 *
 * Bindings are accessed via `import { env } from 'cloudflare:workers'` which is
 * the correct Astro 6 / @astrojs/cloudflare v13 API (Astro.locals.runtime is gone).
 *
 * Environment type declarations are auto-generated by running:
 *   npx wrangler types
 * which writes worker-configuration.d.ts to the project root.
 */

import { env } from 'cloudflare:workers';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Env bindings provided by wrangler.jsonc */
interface CFEnv {
  /** R2 bucket: static CDN (ndjson + poster webp) */
  CDN_STATIC: R2Bucket;
  /** R2 bucket: video CDN (mp4 + vtt) */
  CDN_VIDEO: R2Bucket;
  /** KV namespace: ndjson page cache */
  CDN_CACHE: KVNamespace;
  /** Assets binding (Cloudflare Workers Assets) */
  ASSETS: Fetcher;
  /** Cloudflare Images binding */
  IMAGES: ImagesBinding;
}

// Cast the opaque env to our typed interface.
// Wrangler types (worker-configuration.d.ts) will enforce this at build time.
const cfEnv = env as unknown as CFEnv;

// ---------------------------------------------------------------------------
// KV TTL constants (seconds)
// ---------------------------------------------------------------------------
const KV_TTL_INDEX = 60 * 60 * 4;   // 4 h — index pages change infrequently
const KV_TTL_DETAIL = 60 * 60 * 12; // 12 h — detail files are even more stable
const KV_TTL_SEASON = 60 * 30;       // 30 min — season lists update more often

// ---------------------------------------------------------------------------
// Low-level helpers
// ---------------------------------------------------------------------------

/** Read a UTF-8 text object from R2. Returns null if not found. */
async function r2GetText(bucket: R2Bucket, key: string): Promise<string | null> {
  try {
    const obj = await bucket.get(key);
    if (!obj) return null;
    return await obj.text();
  } catch {
    return null;
  }
}

/** Read a binary object from R2. Returns null if not found. */
async function r2GetArrayBuffer(
  bucket: R2Bucket,
  key: string
): Promise<ArrayBuffer | null> {
  try {
    const obj = await bucket.get(key);
    if (!obj) return null;
    return await obj.arrayBuffer();
  } catch {
    return null;
  }
}

/**
 * KV-cached R2 text read.
 *
 * Checks KV first; on miss reads R2 and writes result to KV with the
 * given TTL.  Falls back to HTTP fetch if both R2 and KV are unavailable
 * (e.g. local Node dev without workerd).
 */
async function cachedText(
  kvKey: string,
  r2Key: string,
  httpFallbackUrl: string,
  ttl: number
): Promise<string | null> {
  // 1. KV cache hit
  try {
    const cached = await cfEnv.CDN_CACHE.get(kvKey);
    if (cached !== null) return cached;
  } catch {
    // KV not available — skip to R2
  }

  // 2. R2 read
  let text: string | null = null;
  try {
    text = await r2GetText(cfEnv.CDN_STATIC, r2Key);
  } catch {
    // R2 not available — skip to HTTP
  }

  // 3. HTTP fallback (local dev / preview without real R2)
  if (text === null) {
    try {
      const res = await fetch(httpFallbackUrl);
      if (res.ok) text = await res.text();
    } catch {
      return null;
    }
  }

  // Write to KV (fire-and-forget — don't block the response)
  if (text !== null) {
    try {
      cfEnv.CDN_CACHE.put(kvKey, text, { expirationTtl: ttl }).catch(() => {});
    } catch {
      // KV write failure is non-fatal
    }
  }

  return text;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

const STATIC_BASE = 'https://static.ma3ak.top';
const VIDEO_BASE  = 'https://s001.mogcdn.com';

/**
 * Fetch a paginated ndjson index file.
 *
 * R2 key pattern:  `{type}/index.{page}.ndjson`
 *   e.g.           `movies/index.1.ndjson`
 */
export async function fetchIndexPage(
  type: 'movies' | 'tv',
  page: number
): Promise<string | null> {
  const r2Key  = `${type}/index.${page}.ndjson`;
  const kvKey  = `idx:${type}:${page}`;
  const httpUrl = `${STATIC_BASE}/${r2Key}`;
  return cachedText(kvKey, r2Key, httpUrl, KV_TTL_INDEX);
}

/**
 * Fetch a detail ndjson for a specific item.
 *
 * R2 key pattern:  `{type}/{prefix}/{id}/{id}.ndjson`
 *   e.g.           `movies/20/2097884/2097884.ndjson`
 */
export async function fetchDetailNdjson(
  type: 'movies' | 'tv',
  prefix: string,
  id: string
): Promise<string | null> {
  const r2Key   = `${type}/${prefix}/${id}/${id}.ndjson`;
  const kvKey   = `det:${type}:${id}`;
  const httpUrl = `${STATIC_BASE}/${r2Key}`;
  return cachedText(kvKey, r2Key, httpUrl, KV_TTL_DETAIL);
}

/**
 * Fetch a cdn.ndjson (video metadata) for a specific item.
 * Used by PlayerIsland to resolve the video URL.
 *
 * R2 key pattern:  `{type}/{prefix}/{id}/cdn.ndjson`
 */
export async function fetchCdnNdjson(
  type: 'movies' | 'tv',
  prefix: string,
  id: string
): Promise<string | null> {
  const r2Key   = `${type}/${prefix}/${id}/cdn.ndjson`;
  const kvKey   = `cdn:${type}:${id}`;
  const httpUrl = `${STATIC_BASE}/${r2Key}`;
  return cachedText(kvKey, r2Key, httpUrl, KV_TTL_DETAIL);
}

/**
 * Fetch a season episode list ndjson.
 *
 * R2 key pattern:  `tv/{prefix}/{id}/cdn.s{season}.ndjson`
 *   e.g.           `tv/20/2096455/cdn.s01.ndjson`
 */
export async function fetchSeasonNdjson(
  prefix: string,
  id: string,
  seasonPadded: string
): Promise<string | null> {
  const r2Key   = `tv/${prefix}/${id}/cdn.s${seasonPadded}.ndjson`;
  const kvKey   = `sea:tv:${id}:s${seasonPadded}`;
  const httpUrl = `${STATIC_BASE}/${r2Key}`;
  return cachedText(kvKey, r2Key, httpUrl, KV_TTL_SEASON);
}

/**
 * Check whether a season ndjson exists (HEAD-equivalent via R2).
 * Returns true if the object exists in R2 or if HTTP returns 200.
 */
export async function seasonExists(
  prefix: string,
  id: string,
  seasonPadded: string
): Promise<boolean> {
  // Try R2 first
  try {
    const head = await cfEnv.CDN_STATIC.head(
      `tv/${prefix}/${id}/cdn.s${seasonPadded}.ndjson`
    );
    if (head !== null) return true;
  } catch {
    // R2 unavailable — fall through to HTTP
  }
  // HTTP fallback
  try {
    const res = await fetch(
      `${STATIC_BASE}/tv/${prefix}/${id}/cdn.s${seasonPadded}.ndjson`,
      { method: 'HEAD' }
    );
    return res.ok;
  } catch {
    return false;
  }
}

/**
 * Serve a poster image directly from R2.
 * Returns a Response suitable for use in an API route, or null to let
 * the caller fall back to proxying the HTTP URL.
 *
 * R2 key pattern:  `{type}/{prefix}/{id}/{id}.webp`
 */
export async function fetchPosterFromR2(
  type: 'movies' | 'tv',
  prefix: string,
  id: string
): Promise<Response | null> {
  try {
    const obj = await cfEnv.CDN_STATIC.get(`${type}/${prefix}/${id}/${id}.webp`);
    if (!obj) return null;
    const headers = new Headers();
    headers.set('Content-Type', 'image/webp');
    headers.set('Cache-Control', 'public, max-age=86400, s-maxage=86400');
    if (obj.httpEtag) headers.set('ETag', obj.httpEtag);
    return new Response(obj.body, { headers });
  } catch {
    return null;
  }
}

/**
 * Invalidate a cached ndjson entry in KV.
 * Useful when content is updated and you need to bust the cache.
 */
export async function invalidateCache(kvKey: string): Promise<void> {
  try {
    await cfEnv.CDN_CACHE.delete(kvKey);
  } catch {
    // non-fatal
  }
}

/** Expose raw env for advanced use-cases (e.g. D1 queries). */
export { cfEnv };
